### ISSUE TITLE
No AdminController

### ISSUE THREAD

**Issue by londoh** [Jeroen-G/laravel-photo-gallery#30]
Hi

just testing your package and I get this error when running the 2.0 branch in L5:

```
[ReflectionException]                                                         
  Class JeroenG\LaravelPhotoGallery\Controllers\AdminController does not exist
```

there is a route set, but of course there is no admincontroller (yet? )

regards

l.

**Comment by Jeroen-G** [comment]
You're right, it is not there yet. ;-)

**Comment by Krato** [comment]
And???

**Comment by Jeroen-G** [comment]
I don't have enough time to work on this.

**Comment by Krato** [comment]
Ok, so take your time ;)

**Comment by Jeroen-G** [comment]
Feel free to fork and place a Pull Request on the 2.0 branch :smile:
