### ISSUE TITLE
Redirect problem to 'gallery' route on 2.0 branch

### ISSUE THREAD

**Issue by londoh** [Jeroen-G/laravel-photo-gallery#31]
the standard install appears to create a dir called gallery.
this conflicts with the route called gallery

and the whole thing just redirects round and round and...

regards

l.

**Comment by Jeroen-G** [comment]
With which versions?

**Comment by Jeroen-G** [comment]
The 2.0 branch is under development, and probably consists more of bugs than of features :P
Thanks for reporting!
