### ISSUE TITLE
cant install on Laravel 5.1

### ISSUE THREAD

**Issue by dbr0** [Jeroen-G/laravel-photo-gallery#32]
Hi, I'm new to all this so please be tolerant if I'm doing something wrong. Thanks.
## I have problems installing package on Laravel 5.1.7. Here's the `composer require` output:

Using version ^1.2 for jeroen-g/laravel-photo-gallery
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for jeroen-g/laravel-photo-gallery ^1.2 -> satisfiable by jeroen-g/laravel-photo-gallery[v1.2].
    - Conclusion: remove laravel/framework v5.1.7
    - Conclusion: don't install laravel/framework v5.1.7
    - jeroen-g/laravel-photo-gallery v1.2 requires illuminate/support 4.2.\* -> satisfiable by illuminate/support[v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
    - don't install illuminate/support v4.2.1|don't install laravel/framework v5.1.7
    - don't install illuminate/support v4.2.12|don't install laravel/framework v5.1.7
    - don't install illuminate/support v4.2.16|don't install laravel/framework v5.1.7
    - don't install illuminate/support v4.2.17|don't install laravel/framework v5.1.7
    - don't install illuminate/support v4.2.2|don't install laravel/framework v5.1.7
    - don't install illuminate/support v4.2.3|don't install laravel/framework v5.1.7
    - don't install illuminate/support v4.2.4|don't install laravel/framework v5.1.7
    - don't install illuminate/support v4.2.5|don't install laravel/framework v5.1.7
    - don't install illuminate/support v4.2.6|don't install laravel/framework v5.1.7
    - don't install illuminate/support v4.2.7|don't install laravel/framework v5.1.7
    - don't install illuminate/support v4.2.8|don't install laravel/framework v5.1.7
    - don't install illuminate/support v4.2.9|don't install laravel/framework v5.1.7
    - Installation request for laravel/framework == 5.1.7.0 -> satisfiable by laravel/framework[v5.1.7].
## Installation failed, reverting ./composer.json to its original content.

Any thoughts when will the package be available on 5.1.7 version?
Also is there a demo somewhere to see the app in action?

**Comment by Jeroen-G** [comment]
Version 1.\* works only on Laravel 4.*
I am working on version 2, which would work on Laravel 5.\* but this takes some time. So you could try requiring version `2.0.x-dev` instead, but it will very likely contain bugs and work not as expected. If you yourself have some extra time, you are welcome to place Pull Requests on the 2.0 branch with bug repairs or new features.
There is currently also not a demo online.
